apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: transaction-web-app
  labels:
    app: transaction-web-app
    role: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-web-app
  template:
    metadata:
      labels:
        app: transaction-web-app
    spec:
      containers:
        - name: transaction-web
          image: 864981757274.dkr.ecr.ap-east-1.amazonaws.com/test/transaction-web:latest
          ports:
            - containerPort: 8080

          resources:
            requests:
              cpu: ".5"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "2Gi"

      # imagePullSecrets:
      #   - name: regcred # 需要提前创建 AWS ECR的访问凭证

---
apiVersion: apps/v1
kind: HorizontalPodAutoscaler
metadata:
  name: transaction-web-app-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: transaction-web-app
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
