apiVersion: v1
kind: Service
metadata:
  name: transaction-web-service
spec:
  selector:
    app: transaction-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
